apiVersion: v1
kind: Secret
metadata:
  name: wedding-telegram-bot-secret
  namespace: dev-backend-services
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8458433644:AAFGSsQE2-RrClEjVIc0ZymE-eHjBa1viEw"
  DATABASE_URL: "postgresql://wedding_bot:wedding_bot_pass@postgres:5432/wedding_bot"
