apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wedding-telegram-bot-vault
  namespace: dev-backend-services
spec:
  type: kv-v2

  # Mount path
  mount: secret

  # Path to secret in Vault
  path: dev-backend-services/wedding-telegram-bot-secret

  # Destination K8s Secret
  destination:
    name: wedding-telegram-bot-secret
    create: true

  # Refresh interval
  refreshAfter: 30s

  # HMACSecretData - verify secret integrity
  hmacSecretData: true
